import { PGlite } from '@electric-sql/pglite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;
create schema auth;create schema storage;create schema extensions;
create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
grant usage on schema public,auth,storage to anon,authenticated,service_role;
create table storage.buckets(id text primary key,name text,public boolean);
create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text,owner_id text);
alter table storage.objects enable row level security;grant select,insert,update,delete on storage.objects to authenticated,anon;
create function public.gen_random_bytes(n integer) returns bytea language sql as $$select decode(repeat(replace(gen_random_uuid()::text,'-',''),4),'hex')::bytea $$;
create function extensions.gen_random_bytes(n integer) returns bytea language sql as $$select public.gen_random_bytes(n) $$;`);
const rd=f=>fs.readFileSync(new URL(f,import.meta.url),'utf8');
await db.exec(rd('./fixtures/schema-v1.sql').replace('create extension if not exists pgcrypto;',''));
for(const f of ['multi-agencias','hierarquia','squads','convites','divisoes']) await db.exec(rd(`../supabase/${f}.sql`));
const A={a:'10000000-0000-4000-8000-000000000001',b:'10000000-0000-4000-8000-000000000002'};
const P={admin:null,dono:['b','dono'],head1:['b','head'],head2:['b','head'],des1:['b','designer'],des2:['b','designer'],traf:['b','gestor_trafego'],semSquad:['b','designer'],outraAg:['a','head'],desA:['a','designer'],livre:null,livre2:null};
const id={};let i=1;for(const k in P)id[k]=`40000000-0000-4000-8000-${String(i++).padStart(12,'0')}`;
await db.exec(`insert into auth.users values ${Object.keys(P).map(k=>`('${id[k]}','${k}@x.test',now())`).join(',')};
insert into administradores values('${id.admin}');
insert into agencia_usuarios(agencia_id,usuario_id,papel) values ${Object.entries(P).filter(([,v])=>v).map(([k,[g,p]])=>`('${A[g]}','${id[k]}','${p}')`).join(',')};`);
const q=(s,p)=>db.query(s,p), rows=async(s,p)=>(await q(s,p)).rows;
const S1=(await rows(`insert into squads(agencia_id,nome) values($1,'Squad 1') returning id`,[A.b]))[0].id;
const S2=(await rows(`insert into squads(agencia_id,nome) values($1,'Squad 2') returning id`,[A.b]))[0].id;
const SA=(await rows(`insert into squads(agencia_id,nome) values($1,'Squad A') returning id`,[A.a]))[0].id;
await q(`insert into squad_membros values($1,$2),($1,$3),($1,$4),($5,$6),($5,$7),($5,$4),($8,$9)`,[S1,id.head1,id.des1,id.traf,S2,id.head2,id.des2,SA,id.outraAg]);
const C={};const M={};const PO={};
for(const [k,s,g] of [['c1',S1,'b'],['c2',S2,'b'],['c0',null,'b'],['ca',SA,'a']]){
  C[k]=(await rows(`insert into clientes(agencia_id,squad_id,nome,slug,token) values($1,$2,$3,$3,$4) returning id`,[A[g],s,k,k.repeat(12)]))[0].id;
  M[k]=(await rows(`insert into meses(cliente_id,ano_mes,titulo,publicado) values($1,'2026-10','Out',true) returning id`,[C[k]]))[0].id;
  PO[k]=(await rows(`insert into posts(mes_id,titulo,slides) values($1,'P',$2) returning id`,[M[k],JSON.stringify([`midia:${A[g]}/${k}.jpg`])]))[0].id;
  await q(`insert into storage.objects(bucket_id,name) values('midia',$1)`,[`${A[g]}/${k}.jpg`]);
}
let checks=0;const ok=()=>checks++;
async function as(who,fn){await db.exec(`set role authenticated;set request.jwt.claim.sub='${id[who]}';`);try{return await fn();}finally{await db.exec('reset role;');}}
const nomes=async()=>(await rows('select nome from clientes order by nome')).map(r=>r.nome).join(',');
const midias=async()=>(await rows('select name from storage.objects')).map(r=>r.name.split('/')[1]).sort().join(',');
const expect={admin:'c0,c1,c2,ca',dono:'c0,c1,c2',head1:'c1',head2:'c2',des1:'c1',des2:'c2',traf:'c1,c2',semSquad:'',outraAg:'ca',livre:'',desA:'ca'};
for(const [w,e] of Object.entries(expect)) await as(w,async()=>{
  assert.equal(await nomes(),e,w+' clientes');ok();
  assert.equal((await rows('select count(*)::int n from posts'))[0].n,e?e.split(',').length:0,w+' posts');ok();
  assert.equal(await midias(),e?e.split(',').map(x=>x+'.jpg').join(','):'',w+' midia');ok();
});
await as('head1',async()=>{
  assert.equal((await rows('select nome from squads')).map(r=>r.nome).join(),'Squad 1');ok();
  assert.equal((await rows('select link_cliente($1) t',[C.c1]))[0].t,'c1'.repeat(12));ok();
  await assert.rejects(q('select link_cliente($1)',[C.c2]));ok();
  await q(`update meses set publicado=false where id=$1`,[M.c1]);ok();
  await assert.rejects(q(`insert into clientes(agencia_id,squad_id,nome,slug) values($1,$2,'n','n')`,[A.b,S2]));ok();
  await assert.rejects(q(`insert into clientes(agencia_id,nome,slug) values($1,'n','n')`,[A.b]));ok();
  await q(`insert into clientes(agencia_id,squad_id,nome,slug) values($1,$2,'novo1','novo1')`,[A.b,S1]);ok();
  await assert.rejects(q(`update clientes set squad_id=$1 where id=$2`,[S2,C.c1]));ok();
  const l=(await rows('select listar_acessos($1) l',[A.b]))[0].l.map(x=>x.email).sort().join();
  assert.equal(l,'des1@x.test,head1@x.test,traf@x.test');ok();
  assert.ok((await rows('select listar_acessos($1) l',[A.b]))[0].l.every(x=>x.pendente===false));ok();
  await assert.rejects(q('select revogar_acesso($1,$2)',[A.b,id.des2]));ok();
  await assert.rejects(q(`select alterar_papel($1,$2,'editor_video')`,[A.b,id.des2]));ok();
  await q(`select alterar_papel($1,$2,'editor_video')`,[A.b,id.des1]);ok();
  await assert.rejects(q(`select autorizar_acesso($1,'livre@x.test','designer')`,[A.b]));ok();
  await assert.rejects(q(`select autorizar_acesso($1,'livre@x.test','designer',null,$2)`,[A.b,S2]));ok();
  await q(`select autorizar_acesso($1,'livre@x.test','designer','Livre',$2)`,[A.b,S1]);ok();
  await q(`select autorizar_acesso($1,'semSquad@x.test','designer',null,$2)`,[A.b,S1]);ok();
  await assert.rejects(q(`select autorizar_acesso($1,'head2@x.test','designer',null,$2)`,[A.b,S1]));ok();
  await assert.rejects(q('select salvar_squad($1,$2)',[A.b,'Novo']));ok();
  await assert.rejects(q('select definir_membro_squad($1,$2,true)',[S1,id.des2]));ok();
  // tráfego compartilhado: head1 remove só do squad 1
  await q('select revogar_acesso($1,$2)',[A.b,id.traf]);ok();
});
assert.equal((await rows('select count(*)::int n from agencia_usuarios where usuario_id=$1',[id.traf]))[0].n,1);ok();
await as('traf',async()=>{assert.equal(await nomes(),'c2');ok();});
await as('semSquad',async()=>{assert.equal(await nomes(),'c1,novo1');ok();});
assert.equal((await rows(`select papel from agencia_usuarios where usuario_id=$1`,[id.semSquad]))[0].papel,'designer');ok();
await as('head1',async()=>{await q('select revogar_acesso($1,$2)',[A.b,id.livre]);ok();});
assert.equal((await rows('select count(*)::int n from agencia_usuarios where usuario_id=$1',[id.livre]))[0].n,0);ok();
await as('des1',async()=>{
  await assert.rejects(q('select link_cliente($1)',[C.c1]));ok();
  assert.equal((await rows(`delete from posts where id=$1 returning id`,[PO.c1])).length,0);ok();
  await q(`update posts set titulo='ok' where id=$1`,[PO.c1]);ok();
  assert.equal((await rows(`update posts set titulo='x' where id=$1 returning id`,[PO.c2])).length,0);ok();
  await q('select marcar_ajustado($1)',[PO.c1]);ok();
  await assert.rejects(q('select marcar_ajustado($1)',[PO.c2]));ok();
  await assert.rejects(q('select listar_acessos($1)',[A.b]));ok();
  assert.equal((await rows('select listar_squads($1) s',[A.b]))[0].s.length,1);ok();
  await q(`insert into storage.objects(bucket_id,name,owner_id) values('midia',$1,$2)`,[A.b+'/meu.jpg',id.des1]);
  assert.ok((await midias()).includes('meu.jpg'));ok();
});
await as('des2',async()=>{assert.ok(!(await midias()).includes('meu.jpg'));ok();});
await as('dono',async()=>{
  const n=(await rows(`select salvar_squad($1,'Squad 3') s`,[A.b]))[0].s;ok();
  await q('select definir_membro_squad($1,$2,true)',[n,id.des2]);ok();
  await assert.rejects(q('select definir_membro_squad($1,$2,true)',[n,id.outraAg]));ok();
  await q(`update clientes set squad_id=$1 where id=$2`,[n,C.c0]);ok();
  await assert.rejects(q(`update clientes set squad_id=$1 where id=$2`,[SA,C.c0]));ok();
  await assert.rejects(q('select salvar_squad($1,$2)',[A.a,'Invasão']));ok();
  assert.equal((await rows('select listar_squads($1) s',[A.b]))[0].s.length,3);ok();
  await q('select alterar_papel($1,$2,$3)',[A.b,id.head2,'designer']);ok();
  await q('select revogar_acesso($1,$2)',[A.b,id.des2]);ok();
});
assert.equal((await rows('select count(*)::int n from squad_membros where usuario_id=$1',[id.des2]))[0].n,0);ok();
await as('des2',async()=>{assert.equal(await nomes(),'');ok();});
await as('admin',async()=>{assert.equal((await rows('select listar_squads($1) s',[A.a]))[0].s.length,1);ok();});
await q(`insert into convites(usuario_id,codigo_hash,expira_em) values($1,'h',now())`,[id.des1]);
await as('head1',async()=>{assert.equal((await rows('select listar_acessos($1) l',[A.b]))[0].l.find(x=>x.email==='des1@x.test').pendente,true);ok();await assert.rejects(q('select * from convites'));ok();await assert.rejects(q(`select * from convite_por_email('des1@x.test')`));ok();});
await as('desA',async()=>{assert.equal((await rows('select meu_contexto() c'))[0].c.agencias[0].usa_squads,false);ok();await assert.rejects(q('select link_cliente($1)',[C.ca]));ok();});
await as('outraAg',async()=>{
  const ca2=(await rows(`insert into clientes(agencia_id,nome,slug) values($1,'sem squad','sem-squad') returning id`,[A.a]))[0].id;ok();
  assert.equal((await rows('select link_cliente($1) t',[ca2]))[0].t.length>0,true);ok();
  assert.ok((await rows('select listar_acessos($1) l',[A.a]))[0].l.some(x=>x.email==='desA@x.test'&&x.pode_gerir));ok();
  await q(`select autorizar_acesso($1,'livre2@x.test','designer')`,[A.a]);ok();
  await assert.rejects(q('select salvar_squad($1,$2)',[A.a,'Nao']));ok();
  await q('select revogar_acesso($1,$2)',[A.a,id.desA]);ok();
});
await as('livre2',async()=>{assert.equal((await rows('select nome from clientes order by nome')).map(r=>r.nome).join(),'ca,sem squad');ok();});
await as('dono',async()=>{assert.equal((await rows('select meu_contexto() c'))[0].c.agencias[0].usa_squads,true);ok();});
await db.exec('set role anon');
await assert.rejects(q('select listar_squads($1)',[A.b]));ok();
assert.equal((await rows(`select registrar_aprovacao($1,$2,'aprovado',null,'C') r`,['c2'.repeat(12),PO.c2]))[0].r.status,'aprovado');ok();
await db.exec('reset role');
console.log('PASS:',checks,'squad checks: per-squad visibility, media, head scope, shared members, squad management.');
await db.close();
